store/cart/urls.py
from django.urls import path

from cart import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_view, name='cart'),
    path('add/', views.cart_add, name='cart_add'),
    path('update/<int:product_id>', views.cart_update, name='cart_update'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove')
]

store/main/api/urls.py
from django.urls import path

from . import views


app_name = 'main'

urlpatterns = [
    path('categories/', views.CategoryListView.as_view(), name='category_list'),
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('products/<pk>/', views.ProductDetailView.as_view(), name='product_detail'),
]

store/main/urls.py
from django.urls import path

from main import views


app_name = 'main'

urlpatterns = [
    path('', views.shop_view, name='shop'),
    path('category/<str:category_slug>', views.category_view, name='category'),
    path('product/<str:product_slug>', views.product_view, name='product'),
    path('search/', views.search_view, name='search'),
]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),
    path('api/', include('main.api.urls', namespace='api')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/users/urls.py
from django.urls import path

from users import views


app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
]

store/main/models.py
from django.db import models
from django.urls import reverse


class ProductManager(models.Manager):
    def all(self, *args, **kwargs):
        return super().get_queryset().filter(available=True)


class Category(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('title',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('main:category', kwargs={'category_slug': self.slug})


def get_image_path(instance, filename):
    filename = f'{instance.slug}.{filename.split(".")[1]}'
    return f'products/{instance.slug}/{filename}'


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    slug = models.SlugField(max_length=150, unique=True)
    short_desc = models.TextField(blank=True)
    desc = models.TextField(blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    image = models.ImageField(upload_to=get_image_path, blank=True)
    available = models.BooleanField(default=True)
    objects = ProductManager()

    class Meta:
        ordering = ('title',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('main:product', kwargs={'product_slug': self.slug})

store/main/api/views.py
from rest_framework import generics

from main.models import Category, Product
from .serializers import CategorySerializer, ProductSerializer


class CategoryListView(generics.ListAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


class ProductListView(generics.ListAPIView):
    queryset = Product.objects.all().order_by('id')
    serializer_class = ProductSerializer


class ProductDetailView(generics.RetrieveAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

store/main/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from cart.forms import CartAddProductForm
from main.models import Category, Product


def get_paginator(request, object_list, per_page=10):
    paginator = Paginator(object_list, per_page)
    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)
    is_paginated = page.has_other_pages()

    prev_url = f'?page={page.previous_page_number()}' if page.has_previous() else ''
    next_url = f'?page={page.next_page_number()}' if page.has_next() else ''

    context = {
        'content_objects': page,
        'is_paginated': is_paginated,
        'prev_url': prev_url,
        'next_url': next_url
    }

    return context


def shop_view(request):
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'cart_product_form': cart_product_form,
        'categories': categories,
    }
    paginator_context = get_paginator(request, products, 6)
    context.update(paginator_context)

    return render(request, 'main/shop.html', context)


def product_view(request, product_slug):
    categories = Category.objects.all()
    product = get_object_or_404(Product, slug=product_slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'cart_product_form': cart_product_form,
        'categories': categories,
        'product': product,
    }

    return render(request, 'main/product.html', context)


def category_view(request, category_slug):
    categories = Category.objects.all()
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(available=True).filter(category=category)
    cart_product_form = CartAddProductForm()
    context = {
        'cart_product_form': cart_product_form,
        'categories': categories,
        'category': category,
    }
    paginator_context = get_paginator(request, products, 6)
    context.update(paginator_context)

    return render(request, 'main/shop.html', context)


def search_view(request):
    products = Product.objects.all()
    query = request.GET.get('q')
    founded = []
    # т.к. SQLite не поддерживает регистронезависимый поиск Unicode,
    # поэтому нельзя использовать __icontains
    for product in products:
        if query.lower() in product.title.lower():
            founded.append(product)

    categories = Category.objects.all()
    cart_product_form = CartAddProductForm()

    context = {
        'cart_product_form': cart_product_form,
        'categories': categories,
        'founded': founded
    }

    return render(request, 'main/search.html', context)

store/main/templates/main/_base.html
{% load static %}
{% static 'main/img/no_image.png' as no_image %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}{% endblock %}Магазин</title>

  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'main/css/styles.css' %}" rel="stylesheet">
</head>
<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'main:shop' %}">Магазин</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:shop' %}">Каталог</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cart:cart' %}">
            {% with total_items=cart|length %}
              <i class="fa fa-shopping-cart"></i><span id="badge-count" class="badge badge-primary badge-pill"> {{ total_items }}</span>
            {% endwith %}
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Content -->
  <div class="container">
    {% block content %}{% endblock %}
  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <script src="{% static 'main/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'main/js/bootstrap.bundle.min.js' %}"></script>

  <script type="text/javascript">
    $(document).on('submit', '.add-to-cart', function(e) {
      e.preventDefault();
      product_id = $(this).attr('product-id');
      data = {
        'product_id': product_id,
        'csrfmiddlewaretoken': $('input[name="csrfmiddlewaretoken"]').val(),
        'quantity': $('input[name="quantity"]').val(),
        'update': $('input[name="update"]').val(),
      }
      console.log(product_id)

      $.ajax({
        type: "POST",
        url: "{% url 'cart:cart_add' %}",
        data: data,
        success: function(data){
          $('#badge-count').html(data.cart_total)
          console.log('Success')
        }
      })
    });
  </script>
</body>
</html>

store/main/templates/main/_pagination.html
{% if is_paginated %}
<nav>
  <ul class="pagination justify-content-center">
    <li class="page-item {% if not prev_url %}disabled{% endif %}">
      <a class="page-link" href="{{ prev_url }}" tabindex="-1">Предыдущая</a>
    </li>

    {% for num in content_objects.paginator.page_range %}
      {% if content_objects.number == num %}
        <li class="page-item active">
          <a class="page-link" href="?page={{ num }}">{{ num }} <span class="sr-only">(current)</span></a>
        </li>
      {% elif num > content_objects.number|add:-3 and num < content_objects.number|add:3 %}
        <li class="page-item">
          <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
      {% endif %}
    {% endfor %}

    <li class="page-item {% if not next_url %}disabled{% endif %}">
      <a class="page-link" href="{{ next_url }}">Следующая</a>
    </li>
  </ul>
</nav>
{% endif %}

store/main/templates/main/_sidebar.html
<div class="col-lg-3">

  <h1 class="my-4">Каталог</h1>

  <div class="mb-3">
    <form class="form-inline my-2 my-lg-0" action="{% url 'main:search' %}" method="get">
      <div class="form-group">
        <input type="search" class="form-control" name='q' placeholder="Поиск по товарам">
      </div>
    </form>
  </div>

  <div class="list-group mb-3">
  {% for cat in categories %}
    <a href="{{ cat.get_absolute_url }}" class="{% if category.slug == cat.slug %}active{% endif %} list-group-item">
      {{ cat.title }}
    </a>
  {% endfor %}
  </div>

</div>

store/main/templates/main/product.html
{% extends 'main/_base.html' %}

{% block title %}{{ product.title }} - {% endblock %}

{% block content %}
<div class="row mb-4">
  {% include 'main/_sidebar.html' %}
  <div class="col-lg-9">
    <div class="card mt-4">
      <img class="card-img-top img-fluid" src="{% if product.image %}{{ product.image.url }}{% else %}{{ no_image }}{% endif %}" alt="">
      <div class="card-body">
        <h3 class="card-title">{{ product.title }}</h3>
        <p class="card-text">{{ product.desc }}</p>
      </div>
      <div class="card-footer text-right">
        <h4>{{ product.price }} руб.</h4>
        <form action="{% url 'cart:cart_add'%}" method="post" class="add-to-cart" product-id="{{ product.id }}">
          {% csrf_token %}
          {{ cart_product_form }}
          <button type="submit" class="btn btn-outline-primary">Добавить в корзину</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

store/main/templates/main/search.html
{% extends 'main/_base.html' %}

{% block title %}Результаты поиска - {% endblock %}

{% block content %}
<div class="row">
  {% include 'main/_sidebar.html' %}
  <div class="col-lg-9">
    <h2 class="my-4">Найдено товаров: {{ founded|length }}</h2>
    <div class="row mt-4">
    {% for product in founded %}
      <div class="col-lg-4 col-md-6 mb-4">
        <div class="card h-100">
          <a href="{{ product.get_absolute_url }}">
            <img class="card-img-top" src="{% if product.image %}{{ product.image.url }}{% else %}{{ no_image }}{% endif %}" alt="">
          </a>
          <div class="card-body">
            <h5 class="card-title">
              <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
            </h5>
            <h5>{{ product.price }} руб.</h5>
            <p class="card-text">{{ product.short_desc }}</p>
          </div>
          <div class="card-footer">
            <form action="{% url 'cart:cart_add'%}" method="post" class="add-to-cart" product-id="{{ product.id }}">
              {% csrf_token %}
              <div style="display:none">{{ cart_product_form }}</div>
              <button type="submit" class="btn btn-outline-primary btn-block">Добавить в корзину</button>
            </form>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

store/main/templates/main/shop.html
{% extends 'main/_base.html' %}

{% block title %}Каталог - {% endblock %}

{% block content %}
<div class="row">
  {% include 'main/_sidebar.html' %}
  <div class="col-lg-9">
    <div class="row mt-4">
    {% for product in content_objects %}
      <div class="col-lg-4 col-md-6 mb-4">
        <div class="card h-100">
          <a href="{{ product.get_absolute_url }}">
            <img class="card-img-top" src="{% if product.image %}{{ product.image.url }}{% else %}{{ no_image }}{% endif %}" alt="">
          </a>
          <div class="card-body">
            <h5 class="card-title">
              <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
            </h5>
            <h5>{{ product.price }} руб.</h5>
            <p class="card-text">{{ product.short_desc }}</p>
          </div>
          <div class="card-footer">
            <form action="{% url 'cart:cart_add'%}" class="add-to-cart" product-id="{{ product.id }}">
              {% csrf_token %}
              <div style='display:none'>{{ cart_product_form }}</div>
              <button type="submit" class="btn btn-outline-primary btn-block">Добавить в корзину</button>
            </form>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
    {% include 'main/_pagination.html' %}
  </div>
</div>
{% endblock %}