store/cart/urls.py
from django.urls import path

from cart import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_view, name='cart'),
    path('add/', views.cart_add, name='cart_add'),
    path('update/<int:product_id>', views.cart_update, name='cart_update'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove')
]

store/main/urls.py
from django.urls import path

from main import views


app_name = 'main'

urlpatterns = [
    path('', views.shop_view, name='shop'),
    path('category/<str:category_slug>', views.category_view, name='category'),
    path('product/<str:product_slug>', views.product_view, name='product'),
    path('search/', views.search_view, name='search'),
]

store/orders/urls.py
from django.urls import path

from orders import views


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create_view, name='order_create'),
]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),
    path('api/', include('main.api.urls', namespace='api')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/cart/models.py
from django.db import models

# Create your models here.

store/cart/forms.py
from django import forms


QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 20)]


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(label='Количество',
                                  required=True,
                                  initial=1,
                                  min_value=1)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

store/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.http import JsonResponse

from main.models import Product
from cart.cart import Cart
from cart.forms import CartAddProductForm


def cart_view(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    context = {
        'cart': cart
    }

    return render(request, 'cart/cart.html', context)


@require_POST
def cart_add(request):
    cart = Cart(request)
    product = get_object_or_404(Product, id=request.POST.get('product_id'))
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        c_data = form.cleaned_data
        cart.add(product=product,
                 quantity=c_data['quantity'],
                 update=c_data['update'],)

    return JsonResponse({'cart_total': len(cart)})


@require_POST
def cart_update(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        c_data = form.cleaned_data
        cart.add(product=product,
                 quantity=c_data['quantity'],
                 update=c_data['update'],)

    return redirect('cart:cart')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)

    return redirect('cart:cart')

store/cart/templates/cart/cart.html
{% extends 'main/_base.html' %}

{% block title %}Корзина - {% endblock %}

{% block content %}
<h1 class="my-4">Корзина</h1>
{% if not cart %}<p>Корзина пуста</p>{% else %}
<table id="cart" class="table table-hover table-condensed">
  <thead>
    <tr>
      <th style="width:48%">Товар</th>
      <th style="width:14%" class="text-center">Цена</th>
      <th style="width:6%">Количество</th>
      <th style="width:18%" class="text-center">Стоимость</th>
      <th style="width:14%"></th>
    </tr>
  </thead>
  <tbody>
    {% for item in cart %}
      {% with product=item.product %}
      <tr>
        <td data-th="Product">
          <div class="row">
            <div class="col-sm-3 hidden-xs">
              <a href="{{product.get_absolute_url}}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{{ no_image }}{% endif %}" alt="" class="img-fluid" />
              </a>
            </div>
            <div class="col-sm-9">
              <h4 class="nomargin">
                <a href="{{product.get_absolute_url}}">{{ product.title }}</a>
              </h4>
              <p>{{ product.short_desc }}</p>
            </div>
          </div>
        </td>
        <td data-th="Price" class="text-center">{{ item.price }} руб.</td>
        <td data-th="Quantity">
          <form id='update-quantity-{{ product.id }}' action="{% url 'cart:cart_update' product.id %}" method="post">
            {% csrf_token %}
            {{ item.update_quantity_form.quantity }}
            {{ item.update_quantity_form.update }}
          </form>
        </td>
        <td data-th="Subtotal" class="text-center">{{ item.total_price }} руб.</td>
        <td class="actions" data-th="">
          <button form="update-quantity-{{ product.id }}" type="submit" class="btn btn-info btn-sm"><i class="fa fa-refresh"></i></button>
          <a href="{% url 'cart:cart_remove' product.id %}">
            <button class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i></button>
          </a>
        </td>
      </tr>
      {% endwith %}
    {% endfor %}
  </tbody>
  <tfoot>
    <tr>
      <td><a href="{% url 'main:shop' %}" class="btn btn-warning">Вернуться в каталог</a></td>
      <td class="hidden-xs"></td>
      <td colspan="2" class="hidden-xs text-right"><strong>Итого: {{ cart.get_total_price }} руб.</strong></td>
      <td><a href="{% url 'orders:order_create' %}" class="btn btn-success btn-block">Оформить</a></td>
    </tr>
  </tfoot>
</table>
{% endif %}
{% endblock %}